version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - "APP_ENV=local"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - app
